# PETER:
# Configuration for streaming Transformer-Transducer (T-T) training
# For improving the performance, a Mask-CTC model with identical encoder setting
# needs to be pretrained and initialized in the encoder of the T-T model. 
# Initialization can be achieved in asr.sh with pretrained_model variable
# Based on exp env, batch_size and accum_grad should be adjusted


batch_size: 16
accum_grad: 8
max_epoch: 200
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

model_conf:
    ctc_weight: 0.0
    report_cer: False
    report_wer: False


encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true


decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 300
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 300

optim: adam
optim_conf:
    lr: 0.0015
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000


specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
